// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"genuine_douyin/apps/user/internal/logic"
	"genuine_douyin/apps/user/internal/svc"
	"genuine_douyin/apps/user/user"
)

type UserSrvServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserSrvServer
}

func NewUserSrvServer(svcCtx *svc.ServiceContext) *UserSrvServer {
	return &UserSrvServer{
		svcCtx: svcCtx,
	}
}

func (s *UserSrvServer) Register(ctx context.Context, in *user.DouyinUserRegisterRequest) (*user.DouyinUserRegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserSrvServer) Login(ctx context.Context, in *user.DouyinUserRegisterRequest) (*user.DouyinUserRegisterResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserSrvServer) GetUserById(ctx context.Context, in *user.DouyinUserRequest) (*user.DouyinUserResponse, error) {
	l := logic.NewGetUserByIdLogic(ctx, s.svcCtx)
	return l.GetUserById(in)
}
