// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"genuine_douyin/apps/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/douyin/user/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/douyin/user/register",
				Handler: RegisterHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthJWT},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/douyin/user",
					Handler: UserInfoHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthJWT},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/douyin/publish/action",
					Handler: PublishActionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/douyin/publish/list",
					Handler: PublishListHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.IsLogin},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/douyin/feed",
					Handler: FeedHandler(serverCtx),
				},
			}...,
		),
	)
}
