// Code generated by goctl. DO NOT EDIT.
// Source: relation.proto

package server

import (
	"context"

	"genuine_douyin/apps/relation/internal/logic"
	"genuine_douyin/apps/relation/internal/svc"
	"genuine_douyin/apps/relation/relation"
)

type RelationSrvServer struct {
	svcCtx *svc.ServiceContext
	relation.UnimplementedRelationSrvServer
}

func NewRelationSrvServer(svcCtx *svc.ServiceContext) *RelationSrvServer {
	return &RelationSrvServer{
		svcCtx: svcCtx,
	}
}

func (s *RelationSrvServer) RelationAction(ctx context.Context, in *relation.DouyinRelationActionRequest) (*relation.DouyinRelationActionResponse, error) {
	l := logic.NewRelationActionLogic(ctx, s.svcCtx)
	return l.RelationAction(in)
}

func (s *RelationSrvServer) RelationFollowList(ctx context.Context, in *relation.DouyinRelationFollowListRequest) (*relation.DouyinRelationFollowListResponse, error) {
	l := logic.NewRelationFollowListLogic(ctx, s.svcCtx)
	return l.RelationFollowList(in)
}

func (s *RelationSrvServer) RelationFollowerList(ctx context.Context, in *relation.DouyinRelationFollowerListRequest) (*relation.DouyinRelationFollowerListResponse, error) {
	l := logic.NewRelationFollowerListLogic(ctx, s.svcCtx)
	return l.RelationFollowerList(in)
}
