// Code generated by goctl. DO NOT EDIT.
// Source: comment.proto

package server

import (
	"context"

	"genuine_douyin/apps/comment/comment"
	"genuine_douyin/apps/comment/internal/logic"
	"genuine_douyin/apps/comment/internal/svc"
)

type CommentSrvServer struct {
	svcCtx *svc.ServiceContext
	comment.UnimplementedCommentSrvServer
}

func NewCommentSrvServer(svcCtx *svc.ServiceContext) *CommentSrvServer {
	return &CommentSrvServer{
		svcCtx: svcCtx,
	}
}

func (s *CommentSrvServer) CommentAction(ctx context.Context, in *comment.DouyinCommentActionRequest) (*comment.DouyinCommentActionResponse, error) {
	l := logic.NewCommentActionLogic(ctx, s.svcCtx)
	return l.CommentAction(in)
}

func (s *CommentSrvServer) CommentList(ctx context.Context, in *comment.DouyinCommentListRequest) (*comment.DouyinCommentListResponse, error) {
	l := logic.NewCommentListLogic(ctx, s.svcCtx)
	return l.CommentList(in)
}
