// Code generated by goctl. DO NOT EDIT.
// Source: video.proto

package server

import (
	"context"

	"genuine_douyin/apps/video/internal/logic"
	"genuine_douyin/apps/video/internal/svc"
	"genuine_douyin/apps/video/video"
)

type VideoSrvServer struct {
	svcCtx *svc.ServiceContext
	video.UnimplementedVideoSrvServer
}

func NewVideoSrvServer(svcCtx *svc.ServiceContext) *VideoSrvServer {
	return &VideoSrvServer{
		svcCtx: svcCtx,
	}
}

func (s *VideoSrvServer) GetUserFeed(ctx context.Context, in *video.DouyinFeedRequest) (*video.DouyinFeedResponse, error) {
	l := logic.NewGetUserFeedLogic(ctx, s.svcCtx)
	return l.GetUserFeed(in)
}

func (s *VideoSrvServer) GetVideoById(ctx context.Context, in *video.VideoIdRequest) (*video.Video, error) {
	l := logic.NewGetVideoByIdLogic(ctx, s.svcCtx)
	return l.GetVideoById(in)
}

func (s *VideoSrvServer) PublishAction(ctx context.Context, in *video.DouyinPublishActionRequest) (*video.DouyinPublishActionResponse, error) {
	l := logic.NewPublishActionLogic(ctx, s.svcCtx)
	return l.PublishAction(in)
}

func (s *VideoSrvServer) PublishList(ctx context.Context, in *video.DouyinPublishListRequest) (*video.DouyinPublishListResponse, error) {
	l := logic.NewPublishListLogic(ctx, s.svcCtx)
	return l.PublishList(in)
}
