// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Id            int64  `json:"id"`             //用户ID
	Name          string `json:"name"`           //用户名
	FollowCount   int64  `json:"follow_count"`   //关注总数
	FollowerCount int64  `json:"follower_count"` //粉丝总数
	IsFollow      bool   `json:"is_follow"`      //true-已关注，false-未关注
}

type Status struct {
	StatusCode int64  `json:"status_code"`
	StatusMsg  string `json:"status_msg,omitempty"`
}

type LoginRequest struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type LoginResponse struct {
	Status
	UserId int64  `json:"user_id"`
	Token  string `json:"token"`
}

type RegisterRequest struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type RegisterResponse struct {
	Status
	UserId int64  `json:"user_id"`
	Token  string `json:"token"`
}

type UserInfoRequest struct {
	UserId int64  `form:"user_id"`
	Token  string `form:"token"`
}

type UserInfoResponse struct {
	Status
	User User `json:"user"`
}

type Video struct {
	Id            int64  `json:"id"`
	Author        User   `json:"author"`
	PlayUrl       string `json:"play_url"`
	CoverUrl      string `json:"cover_url"`
	FavoriteCount int64  `json:"favorite_count"`
	CommentCount  int64  `json:"comment_count"`
	IsFavorite    bool   `json:"is_favorite"`
	Title         string `json:"title"`
}

type FeedRequest struct {
	LatestTime string `form:"latest_time,optional"`
	Token      string `form:"token,optional"`
}

type FeedResponse struct {
	Status
	NextTime  int64   `json:"next_time"`
	VideoList []Video `json:"video_list"`
}

type PublishActionRequest struct {
	Data  []byte `form:"data"`
	Token string `form:"token"`
	Title string `form:"title"`
}

type PublishActionResponse struct {
	Status
}

type PublishListRequest struct {
	Token  string `form:"token"`
	UserId string `form:"user_id"`
}

type PublishListResponse struct {
	Status
	VideoList []Video `json:"video_list"`
}
