// Code generated by goctl. DO NOT EDIT.
// Source: video.proto

package videosrv

import (
	"context"

	"genuine_douyin/apps/video/rpc/video"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DouyinFeedRequest           = video.DouyinFeedRequest
	DouyinFeedResponse          = video.DouyinFeedResponse
	DouyinPublishActionRequest  = video.DouyinPublishActionRequest
	DouyinPublishActionResponse = video.DouyinPublishActionResponse
	DouyinPublishListRequest    = video.DouyinPublishListRequest
	DouyinPublishListResponse   = video.DouyinPublishListResponse
	Video                       = video.Video
	VideoIdRequest              = video.VideoIdRequest

	VideoSrv interface {
		GetUserFeed(ctx context.Context, in *DouyinFeedRequest, opts ...grpc.CallOption) (*DouyinFeedResponse, error)
		GetVideoById(ctx context.Context, in *VideoIdRequest, opts ...grpc.CallOption) (*Video, error)
		PublishAction(ctx context.Context, in *DouyinPublishActionRequest, opts ...grpc.CallOption) (*DouyinPublishActionResponse, error)
		PublishList(ctx context.Context, in *DouyinPublishListRequest, opts ...grpc.CallOption) (*DouyinPublishListResponse, error)
	}

	defaultVideoSrv struct {
		cli zrpc.Client
	}
)

func NewVideoSrv(cli zrpc.Client) VideoSrv {
	return &defaultVideoSrv{
		cli: cli,
	}
}

func (m *defaultVideoSrv) GetUserFeed(ctx context.Context, in *DouyinFeedRequest, opts ...grpc.CallOption) (*DouyinFeedResponse, error) {
	client := video.NewVideoSrvClient(m.cli.Conn())
	return client.GetUserFeed(ctx, in, opts...)
}

func (m *defaultVideoSrv) GetVideoById(ctx context.Context, in *VideoIdRequest, opts ...grpc.CallOption) (*Video, error) {
	client := video.NewVideoSrvClient(m.cli.Conn())
	return client.GetVideoById(ctx, in, opts...)
}

func (m *defaultVideoSrv) PublishAction(ctx context.Context, in *DouyinPublishActionRequest, opts ...grpc.CallOption) (*DouyinPublishActionResponse, error) {
	client := video.NewVideoSrvClient(m.cli.Conn())
	return client.PublishAction(ctx, in, opts...)
}

func (m *defaultVideoSrv) PublishList(ctx context.Context, in *DouyinPublishListRequest, opts ...grpc.CallOption) (*DouyinPublishListResponse, error) {
	client := video.NewVideoSrvClient(m.cli.Conn())
	return client.PublishList(ctx, in, opts...)
}
