// Code generated by goctl. DO NOT EDIT.
// Source: favorite.proto

package favoritesrv

import (
	"context"

	"genuine_douyin/apps/favorite/favorite"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DouyinFavoriteActionRequest  = favorite.DouyinFavoriteActionRequest
	DouyinFavoriteActionResponse = favorite.DouyinFavoriteActionResponse
	DouyinFavoriteListRequest    = favorite.DouyinFavoriteListRequest
	DouyinFavoriteListResponse   = favorite.DouyinFavoriteListResponse

	FavoriteSrv interface {
		FavoriteAction(ctx context.Context, in *DouyinFavoriteActionRequest, opts ...grpc.CallOption) (*DouyinFavoriteActionResponse, error)
		FavoriteList(ctx context.Context, in *DouyinFavoriteListRequest, opts ...grpc.CallOption) (*DouyinFavoriteListResponse, error)
	}

	defaultFavoriteSrv struct {
		cli zrpc.Client
	}
)

func NewFavoriteSrv(cli zrpc.Client) FavoriteSrv {
	return &defaultFavoriteSrv{
		cli: cli,
	}
}

func (m *defaultFavoriteSrv) FavoriteAction(ctx context.Context, in *DouyinFavoriteActionRequest, opts ...grpc.CallOption) (*DouyinFavoriteActionResponse, error) {
	client := favorite.NewFavoriteSrvClient(m.cli.Conn())
	return client.FavoriteAction(ctx, in, opts...)
}

func (m *defaultFavoriteSrv) FavoriteList(ctx context.Context, in *DouyinFavoriteListRequest, opts ...grpc.CallOption) (*DouyinFavoriteListResponse, error) {
	client := favorite.NewFavoriteSrvClient(m.cli.Conn())
	return client.FavoriteList(ctx, in, opts...)
}
