// Code generated by goctl. DO NOT EDIT.
// Source: favorite.proto

package server

import (
	"context"

	"genuine_douyin/apps/favorite/favorite"
	"genuine_douyin/apps/favorite/internal/logic"
	"genuine_douyin/apps/favorite/internal/svc"
)

type FavoriteSrvServer struct {
	svcCtx *svc.ServiceContext
	favorite.UnimplementedFavoriteSrvServer
}

func NewFavoriteSrvServer(svcCtx *svc.ServiceContext) *FavoriteSrvServer {
	return &FavoriteSrvServer{
		svcCtx: svcCtx,
	}
}

func (s *FavoriteSrvServer) FavoriteAction(ctx context.Context, in *favorite.DouyinFavoriteActionRequest) (*favorite.DouyinFavoriteActionResponse, error) {
	l := logic.NewFavoriteActionLogic(ctx, s.svcCtx)
	return l.FavoriteAction(in)
}

func (s *FavoriteSrvServer) FavoriteList(ctx context.Context, in *favorite.DouyinFavoriteListRequest) (*favorite.DouyinFavoriteListResponse, error) {
	l := logic.NewFavoriteListLogic(ctx, s.svcCtx)
	return l.FavoriteList(in)
}
