// Code generated by goctl. DO NOT EDIT.
// Source: relation.proto

package relationsrv

import (
	"context"

	"genuine_douyin/apps/relation/relation"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DouyinRelationActionRequest        = relation.DouyinRelationActionRequest
	DouyinRelationActionResponse       = relation.DouyinRelationActionResponse
	DouyinRelationFollowListRequest    = relation.DouyinRelationFollowListRequest
	DouyinRelationFollowListResponse   = relation.DouyinRelationFollowListResponse
	DouyinRelationFollowerListRequest  = relation.DouyinRelationFollowerListRequest
	DouyinRelationFollowerListResponse = relation.DouyinRelationFollowerListResponse

	RelationSrv interface {
		RelationAction(ctx context.Context, in *DouyinRelationActionRequest, opts ...grpc.CallOption) (*DouyinRelationActionResponse, error)
		RelationFollowList(ctx context.Context, in *DouyinRelationFollowListRequest, opts ...grpc.CallOption) (*DouyinRelationFollowListResponse, error)
		RelationFollowerList(ctx context.Context, in *DouyinRelationFollowerListRequest, opts ...grpc.CallOption) (*DouyinRelationFollowerListResponse, error)
	}

	defaultRelationSrv struct {
		cli zrpc.Client
	}
)

func NewRelationSrv(cli zrpc.Client) RelationSrv {
	return &defaultRelationSrv{
		cli: cli,
	}
}

func (m *defaultRelationSrv) RelationAction(ctx context.Context, in *DouyinRelationActionRequest, opts ...grpc.CallOption) (*DouyinRelationActionResponse, error) {
	client := relation.NewRelationSrvClient(m.cli.Conn())
	return client.RelationAction(ctx, in, opts...)
}

func (m *defaultRelationSrv) RelationFollowList(ctx context.Context, in *DouyinRelationFollowListRequest, opts ...grpc.CallOption) (*DouyinRelationFollowListResponse, error) {
	client := relation.NewRelationSrvClient(m.cli.Conn())
	return client.RelationFollowList(ctx, in, opts...)
}

func (m *defaultRelationSrv) RelationFollowerList(ctx context.Context, in *DouyinRelationFollowerListRequest, opts ...grpc.CallOption) (*DouyinRelationFollowerListResponse, error) {
	client := relation.NewRelationSrvClient(m.cli.Conn())
	return client.RelationFollowerList(ctx, in, opts...)
}
